stages:
  - build
  - test
  - analysis
  - deploy
  - notifications

# --------------------------------- Builds -------------------------------------

.linux_build_template: &linux_build_definition
  stage: build
  tags:
    - docker
  script:
    - mkdir -p .build
    - cd .build
    - cmake -DCMAKE_INSTALL_PREFX:PATH=../.install -DCMAKE_BUILD_TYPE=Release -DXI_BUILD_TESTSUITE=ON ..
    - make
  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_JOB_NAME"
    paths: [.build/]
  artifacts:
    paths: [.build/]
  dependencies: []

Ubuntu Bionic - Build:
  <<: *linux_build_definition
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/ubuntu:bionic

openSuse Leap - Build:
  <<: *linux_build_definition
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/opensuse:leap

Windows 10 - Build:
  stage: build
  tags:
    - windows
  script:
    - if not exist ".\.build" mkdir .\.build
    - cd .\.build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFX:PATH=../.install -DCMAKE_BUILD_TYPE=Release -DXI_BUILD_TESTSUITE=ON ..
    - cmake --build . --config Release
  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_JOB_NAME"
    paths: [.build/]
  artifacts:
    paths: [.build/]
  dependencies: []

# --------------------------------- Tests -------------------------------------

.linux_test_template: &linux_test_definition
  stage: test
  tags:
    - docker
  script:
    - cd ./.build
    - ctest -VV

Ubuntu Bionic - Test:
  <<: *linux_test_definition
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/ubuntu:bionic
  dependencies: ["Ubuntu Bionic - Build"]

openSuse Leap - Test:
  <<: *linux_test_definition
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/opensuse:leap
  dependencies: ["openSuse Leap - Build"]

Windows 10 - Test:
  stage: test
  tags:
    - windows
  dependencies: ["Windows 10 - Build"]
  script:
    - cd .\.build
    - ctest -VV

# --------------------------------- Analysis -----------------------------------

CppCheck:
  stage: analysis
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/cppcheck:latest
  script: "/bin/bash ./scripts/ci/CppCheck.sh"
  artifacts:
    paths: 
      - cppcheck.xml
      - .site/
  # only:
  #   - develop
  #   - master

CppLint:
  stage: analysis
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/cpplint:latest
  dependencies: []
  script: "/bin/bash ./scripts/ci/CppLint.sh"
  artifacts:
    paths: 
      - cpplint.xml
      - .site/
  # only:
  #   - develop
  #   - master

# --------------------------------- Deploy -------------------------------------

.linux_deploy_template: &linux_deploy_definition
  stage: deploy
  tags:
    - docker
  script:
    - cd ./.build
    - make install
    - cd ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - .install/

Ubuntu Bionic:
  <<: *linux_deploy_definition
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/ubuntu:bionic
  dependencies: ["Ubuntu Bionic - Build"]

openSuse Leap:
  <<: *linux_deploy_definition
  image: registry.gitlab.com/galaxia-project/blockchain/develop-environments/opensuse:leap
  dependencies: ["openSuse Leap - Build"]

Windows 10:
  stage: deploy
  tags:
    - windows
  dependencies: ["Windows 10 - Build"]
  script:
    - cd .\.build
    - cmake --build . --target install --config Release
    - cd ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - .install/

Docker:
  image: docker:stable
  tags:
    - dind
  before_script: ["docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com"]
  script: bash ./scripts/ci/DeployDocker.sh
  # only:
  #   - develop
  #   - master

pages:
  stage: deploy
  dependencies:
    - CppCheck
    - CppLint
  script: "mv ./.site ./public"
  artifacts:
    paths:
      - public
  # only:
  #   - develop

# --------------------------------- Notifications -------------------------------------

Discord Failure Notification:
  stage: notifications
  image: ubuntu:bionic
  script: bash ./scripts/ci/SendDiscordNotification.sh failure $DISCORD_WEBHOOK
  dependencies: []
  when: on_failure

Discord Success Notification:
  stage: notifications
  image: ubuntu:bionic
  script: bash ./scripts/ci/SendDiscordNotification.sh success $DISCORD_WEBHOOK
  dependencies: []
  when: on_success