image:
  - Visual Studio 2017
  - Ubuntu1804

configuration:
  - Release

platform:
  - x64

environment:
  DiscordNotificationWebHook:
    secure: XlVNvlCfjIaH/0zMWzz8sgsBquVMgsBuNHq2tdTKMuR/RwP0nXyK2jel5ET8wN+a9LMUQ9OMlvOSqe20gMqy2hJZw0PjQLURO2qI60e9+IwrNYLqfWIsW2In/lIszDM81ib3GPL7EyHFV+P0D+QoRRjJAkkThZEu4z4A22C7qjU=

install:
  - sh: |
      sudo apt-get update
      sudo apt-get install -y libboost-all-dev

before_build:
  - git submodule update --init --recursive

build_script:
  # setup c++ environment on windows
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  # select cmake generator and boost version
  - ps: |
      if ($isLinux) {
        $CMakeGenerator = "Unix Makefiles"
        $CMakeBoostArg = ""
      } else {
        $CMakeGenerator = "Visual Studio 15 2017 Win64"
        $CMakeBoostArg = "-DBOOST_ROOT=C:/Libraries/boost_1_67_0"
      }

  # build process
  - ps: |
      New-Item -ItemType Directory -Force -Path .\.build  | Push-Location
      cmake `
        -G "$CMakeGenerator" `
        -DCMAKE_BUILD_TYPE=$configuration `
        -DXI_BUILD_EXECUTABLES=ON `
        -DXI_BUILD_TESTSUITE=ON `
        -DCMAKE_INSTALL_PREFIX:PATH=../.install `
        $CMakeBoostArg `
        ..
      cmake --build . --config $configuration
      cmake --build . --target install --config $configuration
      Pop-Location

  # settings environment for proper artifact naming
  - ps: |
      $env:XiVersion = Get-Content -Path ./VERSION
      if ($env:APPVEYOR_REPO_BRANCH -NotLike "master") {
        $env:XiVersion = "$($env:XiVersion)-$($env:APPVEYOR_REPO_BRANCH)"
      }
      Rename-Item -Path ./.install/bin -NewName "Xi-v$($env:XiVersion)"
      if ($isLinux) {
        $env:ArtifactOS = "Debian 64bit"
      } else {
        $env:ArtifactOS = "Windows 64bit"
      }
    
# Tests
test_script:
  - ps: |
      Push-Location .\.build
      ctest -VV
      Pop-Location

# Uploading artifacts
artifacts:
  - path: .install
    name: "Standalone $(ArtifactOS) - v$(XiVersion)"
on_success:
  - ps: ./scripts/ci/SendDiscordNotification.ps1 success $env:DiscordNotificationWebHook
on_failure:
  - ps: ./scripts/ci/SendDiscordNotification.ps1 failure $env:DiscordNotificationWebHook